import React, { useState } from 'react'
import api from '../services/api'
import { useNavigate } from 'react-router-dom'

export default function AdminCreateUser(){
  const [form, setForm] = useState({ name:'', email:'', phone:'', password:'', role:'hr' });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const navigate = useNavigate();

  const change = (e) => setForm(prev=>({ ...prev, [e.target.name]: e.target.value }));

  const submit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setResult(null);
    try{
      const res = await api.post('/admin/create-user', form);
      setResult(res.data.user || res.data);
    }catch(err){
      const msg = err?.response?.data?.message || err.message || 'Error';
      setResult({ error: msg });
    }finally{ setLoading(false); }
  }

  return (
    <div className="p-6 max-w-2xl mx-auto">
      <h1 className="text-2xl font-bold mb-4">Create User</h1>
      <form className="card space-y-3" onSubmit={submit}>
        <div>
          <label className="block text-sm">Name</label>
          <input name="name" value={form.name} onChange={change} className="w-full p-2 border rounded bg-slate-50 dark:bg-neutral-800 border-slate-300 dark:border-slate-600 dark:text-white" required />
        </div>
        <div>
          <label className="block text-sm">Email</label>
          <input name="email" value={form.email} onChange={change} type="email" className="w-full p-2 border rounded bg-slate-50 dark:bg-neutral-800 border-slate-300 dark:border-slate-600 dark:text-white" required />
        </div>
        <div>
          <label className="block text-sm">Phone</label>
          <input name="phone" value={form.phone} onChange={change} className="w-full p-2 border rounded bg-slate-50 dark:bg-neutral-800 border-slate-300 dark:border-slate-600 dark:text-white" />
        </div>
        <div>
          <label className="block text-sm">Password (optional — autogenerated if blank)</label>
          <input name="password" value={form.password} onChange={change} className="w-full p-2 border rounded bg-slate-50 dark:bg-neutral-800 border-slate-300 dark:border-slate-600 dark:text-white" />
        </div>
        <div>
          <label className="block text-sm">Role</label>
          <select name="role" value={form.role} onChange={change} className="w-full p-2 border rounded bg-slate-50 dark:bg-neutral-800 border-slate-300 dark:border-slate-600 dark:text-white">
            <option value="admin">Admin</option>
            <option value="hr">HR</option>
            <option value="employee">Employee</option>
          </select>
        </div>
        <div className="flex gap-2">
          <button className="btn-primary" disabled={loading}>{loading? 'Creating...' : 'Create User'}</button>
          <button type="button" onClick={()=>navigate('/admin')} className="btn-ghost">Back</button>
        </div>
      </form>

      {result && (
        <div className="mt-4 card">
          {result.error ? (
            <div className="text-red-600">{result.error}</div>
          ) : (
            <div>
              <div className="font-semibold">User created</div>
              <div>ID: {result.id}</div>
              <div>Name: {result.name}</div>
              <div>Email: {result.email}</div>
              {result.tempPassword && <div className="mt-2 text-sm">Temporary password: <strong>{result.tempPassword}</strong></div>}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
